### ISSUE TITLE
I get this error when trying this with unmodified nobuild.c and nobuild.h

### ISSUE THREAD

**Issue by frunjik** [tsoding/nobuild#10]
cl.exe nobuild.c
Microsoft (R) C/C++ Optimizing Compiler Version 19.15.26730 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

nobuild.c
Microsoft (R) Incremental Linker Version 14.15.26730.0
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:nobuild.exe
nobuild.obj
LINK : fatal error LNK1561: entry point must be defined

Windows 10
I am no C expert .. (thats why I wanted to try this ...)

**Comment by frunjik** [comment]
I understand (now) that this is not an issue with the library:

I get it to work by doing:
cl nobuild.c /link /SUBSYSTEM:CONSOLE
Microsoft (R) C/C++ Optimizing Compiler Version 19.15.26730 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

nobuild.c
d:\projects\win\nobuild\nobuild.h(536) : warning C4716: 'remove_ext': must return a value
Microsoft (R) Incremental Linker Version 14.15.26730.0
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:nobuild.exe
/SUBSYSTEM:CONSOLE
nobuild.obj

**Comment by rexim** [comment]
@kolumb hey! Sorry for bothering! Do you know anything about this? Is the `/link /SUBSYSTEM:CONSOLE` thing really necessary? I don't think we are doing it in any of our CIs and it works just fine.

**Comment by kolumb** [comment]
Yeah, I tested on my machine and it works the same way as on CI. Might be connected to the fact that author's compiler has version 19.15.26730 which is two years old version. Not sure if related.
Because I was looking into [documentation of /SUBSYSTEM](https://docs.microsoft.com/en-us/cpp/build/reference/subsystem-specify-subsystem?view=msvc-160) and it says something about `main`. If it's defined - CONSOLE is default. But it says so even for Visual Studio 2015.. Couldn't find anything else.

**Comment by frunjik** [comment]
Indeed, when I compile with vs 2019 - it does work out of the box with one warning:

I think the warning is correct because:
```
const char *remove_ext(const char *path)
{
    WARN("DEPRECATED: Please use `NOEXT(path)` instead of `remove_ext(path)`. `remove_ext(path)` will be removed in the next major release.");
    nobuild__remove_ext(path);
}
```
does indeed not return a value ...

cl nobuild.c
Microsoft (R) C/C++ Optimizing Compiler Version 19.27.29112 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

nobuild.c
C:\Projects\win\nobuild\nobuild.h(536) : warning C4716: 'remove_ext': must return a value
Microsoft (R) Incremental Linker Version 14.27.29112.0
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:nobuild.exe
nobuild.obj
